# Generated by Django 2.0 on 2020-05-10 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('orgname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('approved_field', models.BooleanField()),
                ('add1', models.CharField(max_length=50)),
                ('add2', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.PositiveIntegerField()),
                ('county', models.CharField(max_length=50)),
                ('signed_on', models.DateTimeField()),
                ('volunteer_flag_date', models.DateTimeField(default=datetime.datetime.now)),
                ('list_on_wish_flag', models.BooleanField()),
                ('list_on_wish_flag_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=200)),
                ('organization_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Portal.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('approved_field', models.BooleanField()),
                ('add1', models.CharField(max_length=50)),
                ('add2', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.PositiveIntegerField()),
                ('county', models.CharField(max_length=50)),
                ('signed_on', models.DateTimeField()),
                ('can_flag_connect', models.BooleanField()),
                ('tutor_flag', models.BooleanField()),
                ('tutor_flag_date', models.DateTimeField(default=datetime.datetime.now)),
                ('volunteer_flag_date', models.DateTimeField(default=datetime.datetime.now)),
                ('list_on_wish_flag', models.BooleanField()),
                ('list_on_wish_flag_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer_Work',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('hours', models.PositiveIntegerField()),
                ('date_time', models.DateTimeField()),
                ('proof', models.FileField(upload_to='files/')),
                ('share_email', models.EmailField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.User')),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Portal.User'),
        ),
    ]
