# Generated by Django 2.0 on 2020-05-12 12:53

from django.db import migrations, models
import django.db.models.deletion
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialsModel',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Portal.User')),
                ('credential', oauth2client.contrib.django_util.models.CredentialsField(null=True)),
                ('task', models.CharField(max_length=80, null=True)),
                ('updated_time', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
