# Generated by Django 2.2 on 2020-05-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='token',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
