# Generated by Django 2.0 on 2020-05-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('USER_ID', models.PositiveIntegerField(max_length=10, primary_key=True, serialize=False)),
                ('FIRST_NAME', models.CharField(max_length=100)),
                ('LAST_NAME', models.CharField(max_length=100)),
                ('EMAIL', models.EmailField(max_length=50)),
                ('APPROVED_FIELD', models.BooleanField()),
                ('ADD1', models.CharField(max_length=50)),
                ('ADD2', models.CharField(max_length=50)),
                ('COUNTRY', models.CharField(max_length=50)),
                ('STATE', models.CharField(max_length=50)),
                ('CITY', models.CharField(max_length=50)),
                ('ZIP', models.PositiveIntegerField(max_length=10)),
                ('COUNTY', models.CharField(max_length=50)),
                ('SIGNED_ON', models.DateTimeField()),
                ('CAN_CONNECT_FLAG', models.BooleanField()),
                ('TUTOR_FLAG', models.BooleanField()),
                ('TUTOR_FLAG_DATE', models.DateTimeField()),
                ('LIST_ON_WISH_FLAG', models.BooleanField()),
                ('LIST_ON_WISH_FLAG_DATE', models.DateTimeField()),
            ],
        ),
    ]
