# Generated by Django 2.0 on 2020-05-06 08:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200506_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('ORG_ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ORGNAME', models.CharField(max_length=100)),
                ('EMAIL', models.EmailField(max_length=50)),
                ('APPROVED_FIELD', models.BooleanField()),
                ('ADD1', models.CharField(max_length=50)),
                ('ADD2', models.CharField(max_length=50)),
                ('COUNTRY', models.CharField(max_length=50)),
                ('STATE', models.CharField(max_length=50)),
                ('CITY', models.CharField(max_length=50)),
                ('ZIP', models.PositiveIntegerField()),
                ('COUNTY', models.CharField(max_length=50)),
                ('SIGNED_ON', models.DateTimeField()),
                ('VOLUNTEER_FLAG_DATE', models.DateTimeField(default=datetime.datetime.now)),
                ('LIST_ON_WISH_FLAG', models.BooleanField()),
                ('LIST_ON_WISH_FLAG_DATE', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('SERVICE_ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('SERVICE_NAME', models.CharField(max_length=200)),
                ('ORGANIZATION_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Volunteer_Work',
            fields=[
                ('ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('DESCRIPTION', models.CharField(max_length=200)),
                ('HOURS', models.PositiveIntegerField()),
                ('DATETIME', models.DateTimeField()),
                ('PROOF', models.FileField(upload_to='files/')),
                ('SHARE_EMAIL', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='VOLUNTEER_FLAG_DATE',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='TUTOR_FLAG_DATE',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='volunteer_work',
            name='USER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.AddField(
            model_name='services',
            name='USER_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
